--- DATABASE scratchpay

CREATE DATABASE IF NOT EXISTS `scratchpay`
DEFAULT CHARACTER SET utf8
DEFAULT COLLATE utf8_general_ci;

SET default_storage_engine = INNODB;

CREATE TABLE `scratchpay`.`ROLE` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(32) UNIQUE NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;

CREATE TABLE `scratchpay`.`PERMISSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(32) UNIQUE NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;

CREATE TABLE `scratchpay`.`ROLE_PERMISSION` (
  `ROLE_ID` bigint(20) NOT NULL,
  `PERMISSION_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ROLE_ID`, `PERMISSION_ID`),
  KEY `FK_PERMISSION_ROLE_ID` (`ROLE_ID`),
  KEY `FK_ROLE_PERMISSION_ID` (`PERMISSION_ID`),
  CONSTRAINT `FK_PERMISSION_ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `scratchpay`.`ROLE` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `FK_ROLE_PERMISSION_ID` FOREIGN KEY (`PERMISSION_ID`) REFERENCES `scratchpay`.`PERMISSION` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `scratchpay`.`USER` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(100) NOT NULL,
  `LAST_NAME` VARCHAR(255) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `STATUS` ENUM('ACTIVE', 'INACTIVE') NOT NULL,
  `ROLE_ID` bigint(20) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_USER_ROLE_ID` (`ROLE_ID`),
  CONSTRAINT `FK_USER_ROLE_ID` FOREIGN KEY (`ROLE_ID`) REFERENCES `scratchpay`.`ROLE` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;

CREATE TABLE `scratchpay`.`TOKEN` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `TOKEN` VARCHAR(255) NOT NULL,
  `EXPIRES` DATETIME,
  `CREATE_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8;
